 const data = [
    {id: 0, name: "testimonial-one", quote: "She is a resume and bio whisperer! I know you'll enjoy working with her on making your already stellar background and experience shine even more.", byline:" - Senior Executive, Global Communications/Media Company"},
    {id: 1, name: "testimonial-two", quote: "I had the pleasure of working with Mary Louise during a critical transition in my career, following the financial meltdown of 2008. We were introduced by a mutual friend and her expertise and guidance proved to be invaluable. Mary Louise provided me with the launching pad to capitalize on other opportunities, after 18 years with one employer. She not only helped me create a resume and bio, but she was a great sounding board and resource for career advice. Mary Louise gave me the confidence to promote my accomplishments and pursue senior executive level positions. New doors have opened, my career has blossomed and I will always remain grateful for Mary Louise's support and guidance. I would recommend her to anyone seeking career advisory services.", byline:' - Senior Vice President, US Asset Management Company'},
    {id: 2, name: "testimonial-three", quote: "Confidence: You have the skills. You have done the work and have a successful career. Yet you have not completely recognized those facts – simply because… You are too busy in your role. Enter Mary Louise – not only does she acknowledge and focus your experiences – but she also gives you that ever so needed boost called CONFIDENCE", byline:' - Management and Business Development Professional'},
    {id: 3, name: "testimonial-four", quote: "I have to tell you that I attended a Corporate Board Training and received many compliments from other attendees about my resume and bio. So I gave her name out to several people.", byline:' - Senior Executive - Fortune 100, American Multinational Consumer Goods Company'},
    {id: 4, name: "testimonial-five", quote: " I worked with Mary Louise during my transition from academia into corporate America. Her insights into the job search and interview process were invaluable. She provided the type of information that no book or course could offer. Her incredibly warm personality made every meeting effortless. I plan on continuing to work with her over the course of my career. Now I am pleased to recommend her to anyone who is looking for a dedicated professional to assist them with career planning or professional advancement.", byline:' - Chief of Staff & Associate Vice President for Corporate Relations, a US National University'},
    {id: 5, name: "testimonial-six", quote: `Description of the search strategies and concrete tactics Mary Louise shares - \n 
         'The gift that keep on giving.'`, 
        byline:' - International Development Executive'}
]

export default data;